version: '3'

services:
  productpage:
    build:
      context: .
      dockerfile: Apartado3/Dockerfile_productpage
    environment:
      GROUP_NUM: g15
    ports:
      - "9080:9080"
    container_name: "product-page-g15"
    image: "product-page/g15"
  
  details:
    build:
      context: .
      dockerfile: Apartado3/Dockerfile_details
    environment:
      SERVICE_VERSION: v1
      ENABLE_EXTERNAL_BOOK_SERVICE: "true"
    container_name: "details-g15"
    image: "details/g15"
  
  ratings:
    build:
      context: .
      dockerfile: Apartado3/Dockerfile_ratings
    environment:
      SERVICE_VERSION: v1
    container_name: "ratings-g15"
    image: "ratings/g15"

  
 