version: '3'
services:
  productpage:
    build:
      context: .
      dockerfile: Apartado3/Dockerfile_productpage
    image: "productpage/15"
    container_name: "productpage-15"
    ports: 
      - "9080:9080"
    environment:
      - GROUP_NUM=15

  details:
    build:
      context: .
      dockerfile: Apartado3/Dockerfile_details
    image: "details/15"
    container_name: "details-15"
    environment:
      ENABLE_EXTERNAL_BOOK_SERVIC: "true"
      SERVICE_VERSION: v1

  ratings:
    build:
      context: .
      dockerfile: Apartado3/Dockerfile_ratings
    image: "ratings/15"
    container_name: "ratings-15"
    environment:
      SERVICE_VERSION: v1

