# Dockerfile para ProductPage
FROM python:3.7.7-slim

ENV GROUP_NUM=15
EXPOSE 9080

# Instalamos dependencias del requirements
RUN apt-get update
RUN apt-get install -y git
RUN git clone https://github.com/CDPS-ETSIT/practica_creativa2.git
RUN apt-get update
RUN apt-get install -y python3-pip
WORKDIR /practica_creativa2/bookinfo/src/productpage
RUN pip3 install -r requirements.txt
RUN pip3 install --upgrade requests


# Cambiamos el título y ejecutamos la aplicación con el script productpage_monolith.py
WORKDIR /practica_creativa2/bookinfo/src/productpage
CMD ["python3", "productpage.py", "9080"]

