version: '3'
services:
  productpage:
    build:
      context: .
      dockerfile: Dockerfile_productpage
    environment:
      GROUP_NUMBER: 15
    ports:
      - "9080:9080"
    container_name: "productpage-15"
    image: "productpage/15"

  details:
    build:
      context: .
      dockerfile: Dockerfile_details
    environment:
      SERVICE_VERSION: v2
      ENABLE_EXTERNAL_BOOK_SERVICE: "true"
    ports:
      - "9081:9080"  # Cambiado el puerto local para evitar conflictos
    container_name: "details-15"
    image: "details/15"

  ratings:
    build:
      context: .
      dockerfile: Dockerfile_ratings
    environment:
      SERVICE_VERSION: v2
    ports:
      - "9083:9080"  # Cambiado el puerto local para evitar conflictos
    container_name: "ratings-15"
    image: "ratings/15"

